server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    org.springframework.boot.context.embedded: INFO
    ch.competec: INFO
spring:
  rabbitmq:
    addresses: 172.17.0.2:5672,172.17.0.3:5672
